# table schema queries
CREATE DATABASE IF NOT EXISTS `sample_bank`;

USE `sample_bank`;

CREATE TABLE IF NOT EXISTS `users` (
	`IdUser` INT(11) NOT NULL AUTO_INCREMENT,
	`Username` VARCHAR(50) NOT NULL DEFAULT '',
	`FirstName` VARCHAR(50) NOT NULL DEFAULT '',
	`LastName` VARCHAR(50) NOT NULL DEFAULT '',
	`Email` VARCHAR(50) NOT NULL DEFAULT '',
	`Password` VARCHAR(50) NOT NULL DEFAULT '',
	`ClientToken` VARCHAR(50) NOT NULL DEFAULT '',
	`RegistrationDate` DATETIME NOT NULL,
	PRIMARY KEY (`IdUser`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0;

CREATE TABLE IF NOT EXISTS `credit_cards` (
	`IdCreditCard` INT(11) NOT NULL AUTO_INCREMENT,
	`IdUser` INT(11) NOT NULL,
	`CardNumber` VARCHAR(19) NOT NULL,
	`Cvv` INT(4) NOT NULL,
	`ExpirationMonth` INT(2) NOT NULL,
	`ExpirationYear` INT(4) NOT NULL,
	`AddDate` DATETIME NOT NULL,
	PRIMARY KEY (`IdCreditCard`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0;

CREATE TABLE IF NOT EXISTS `card_amounts` (
	`IdCardAmounts` INT(11) NOT NULL AUTO_INCREMENT,
	`IdCreditCard` INT(11) NOT NULL,
	`Balance` INT(11) NOT NULL,
	`Currency` VARCHAR(3) NOT NULL DEFAULT 'RON',
	`AddDate`DATETIME NOT NULL,
	PRIMARY KEY (`IdCardAmounts`)
)
	COLLATE='utf8_general_ci'
	ENGINE=InnoDB
	AUTO_INCREMENT=0;

CREATE TABLE IF NOT EXISTS `stores` (
	`IdStore` INT(11) NOT NULL AUTO_INCREMENT,
	`StoreName` VARCHAR(30) NOT NULL DEFAULT '',
	`StoreId` VARCHAR(50) NOT NULL DEFAULT '',
	`SecretKey` VARCHAR(50) NOT NULL DEFAULT '',
	`AddDate`DATETIME NOT NULL,
	PRIMARY KEY (`IdStore`)
)
	COLLATE='utf8_general_ci'
	ENGINE=InnoDB
	AUTO_INCREMENT=0;

CREATE TABLE IF NOT EXISTS `client_tokens` (
	`IdClientTokens` INT(11) NOT NULL AUTO_INCREMENT,
	`IdUser` INT(11) NOT NULL,
	`IdStore` INT(11) NOT NULL,
	`ClientToken` VARCHAR(50) NOT NULL DEFAULT '',
	`AddDate`DATETIME NOT NULL,
	PRIMARY KEY (`IdClientTokens`)
)
	COLLATE='utf8_general_ci'
	ENGINE=InnoDB
	AUTO_INCREMENT=0;
